a=10
a+=5
print("The sum is = ",a)
a=15
a-=20
print("The difference is = ",a)
a=25
a*=2
print("The multiplication is = ",a)
a=17
a/=5
print("The division is = ",a)
a=13
a%=3
print("The remainder is = ",a)
a=2
a**=3
print("The exponential is = ",a)