str=input("please enter the word: ")
location=input("whic word you want to change")
ans=input("what alphabet you want to insert")
print("first character is: ",str[0])
print("second character is: ",str[1])
print("third character is: ",str[2])
print("forth character is: ",str[3])
print("fifth character is: ",str[4])
print("sixth character is: ",str[5])
print("seventh character is: ",str[6])
